export const allProducts = [
  {
    name: "Basic Tee",
    category: "T-Shirts",
    color: "Black",
    size: "M",
    price: 24.0,
    imageUrl: "https://placehold.co/400x400/000000/ffffff?text=Basic+Tee",
  },
  {
    name: "Slim-Fit Jeans",
    category: "Jeans",
    color: "Blue",
    size: "L",
    price: 89.0,
    imageUrl: "https://placehold.co/400x400/3B82F6/ffffff?text=Jeans",
  },
  {
    name: "Running Sneakers",
    category: "Shoes",
    color: "White",
    size: "XL",
    price: 120.0,
    imageUrl: "https://placehold.co/400x400/ffffff/000000?text=Sneakers",
  },
  {
    name: "Leather Jacket",
    category: "Jackets",
    color: "Black",
    size: "M",
    price: 250.0,
    imageUrl: "https://placehold.co/400x400/1a1a1a/ffffff?text=Jacket",
  },
  {
    name: "Crewneck Sweatshirt",
    category: "Sweatshirts",
    color: "Gray",
    size: "L",
    price: 55.0,
    imageUrl: "https://placehold.co/400x400/808080/ffffff?text=Sweatshirt",
  },
  {
    name: "V-Neck Tee",
    category: "T-Shirts",
    color: "White",
    size: "S",
    price: 24.0,
    imageUrl: "https://placehold.co/400x400/f0f0f0/000000?text=V-Neck",
  },
  {
    name: "Cargo Shorts",
    category: "Shorts",
    color: "Khaki",
    size: "XL",
    price: 45.0,
    imageUrl: "https://placehold.co/400x400/C3B091/000000?text=Shorts",
  },
  {
    name: "Denim Jacket",
    category: "Jackets",
    color: "Blue",
    size: "L",
    price: 110.0,
    imageUrl: "https://placehold.co/400x400/2563EB/ffffff?text=Denim+Jacket",
  },
  {
    name: "High-Top Sneakers",
    category: "Shoes",
    color: "Black",
    size: "M",
    price: 150.0,
    imageUrl: "https://placehold.co/400x400/111111/ffffff?text=High-Tops",
  },
  {
    name: "Hoodie",
    category: "Sweatshirts",
    color: "Black",
    size: "S",
    price: 65.0,
    imageUrl: "https://placehold.co/400x400/0d0d0d/ffffff?text=Hoodie",
  },
  {
    name: "Graphic Tee",
    category: "T-Shirts",
    color: "Blue",
    size: "L",
    price: 32.0,
    imageUrl: "https://placehold.co/400x400/1D4ED8/ffffff?text=Graphic+Tee",
  },
  {
    name: "Ripped Jeans",
    category: "Jeans",
    color: "Black",
    size: "S",
    price: 95.0,
    imageUrl: "https://placehold.co/400x400/2b2b2b/ffffff?text=Ripped+Jeans",
  },
  {
    name: "Polo Shirt",
    category: "T-Shirts",
    color: "Red",
    size: "M",
    price: 35.0,
    imageUrl: "https://placehold.co/400x400/DC2626/ffffff?text=Polo+Shirt",
  },
  {
    name: "Chino Pants",
    category: "Pants",
    color: "Beige",
    size: "L",
    price: 70.0,
    imageUrl: "https://placehold.co/400x400/F5F5DC/000000?text=Chinos",
  },
  {
    name: "Loafers",
    category: "Shoes",
    color: "Brown",
    size: "M",
    price: 130.0,
    imageUrl: "https://placehold.co/400x400/8B4513/ffffff?text=Loafers",
  },
  {
    name: "Bomber Jacket",
    category: "Jackets",
    color: "Green",
    size: "XL",
    price: 180.0,
    imageUrl: "https://placehold.co/400x400/166534/ffffff?text=Bomber",
  },
  {
    name: "Zip-Up Hoodie",
    category: "Sweatshirts",
    color: "Navy",
    size: "L",
    price: 70.0,
    imageUrl: "https://placehold.co/400x400/000080/ffffff?text=Zip-Up",
  },
  {
    name: "Henley Shirt",
    category: "T-Shirts",
    color: "Gray",
    size: "S",
    price: 28.0,
    imageUrl: "https://placehold.co/400x400/A9A9A9/000000?text=Henley",
  },
  {
    name: "Athletic Shorts",
    category: "Shorts",
    color: "Black",
    size: "M",
    price: 30.0,
    imageUrl: "https://placehold.co/400x400/1c1c1c/ffffff?text=Athletic",
  },
  {
    name: "Trench Coat",
    category: "Jackets",
    color: "Khaki",
    size: "M",
    price: 220.0,
    imageUrl: "https://placehold.co/400x400/BDB76B/000000?text=Trench+Coat",
  },
  {
    name: "Chelsea Boots",
    category: "Shoes",
    color: "Black",
    size: "L",
    price: 175.0,
    imageUrl: "https://placehold.co/400x400/2d2d2d/ffffff?text=Boots",
  },
  {
    name: "Fleece Pullover",
    category: "Sweatshirts",
    color: "Cream",
    size: "XL",
    price: 80.0,
    imageUrl: "https://placehold.co/400x400/FFFDD0/000000?text=Fleece",
  },
  {
    name: "Long Sleeve Tee",
    category: "T-Shirts",
    color: "Green",
    size: "M",
    price: 29.0,
    imageUrl: "https://placehold.co/400x400/228B22/ffffff?text=Long+Sleeve",
  },
  {
    name: "Skinny Jeans",
    category: "Jeans",
    color: "Dark Blue",
    size: "S",
    price: 92.0,
    imageUrl: "https://placehold.co/400x400/00008B/ffffff?text=Skinny+Jeans",
  },
  {
    name: "Oxford Shirt",
    category: "Shirts",
    color: "Light Blue",
    size: "L",
    price: 60.0,
    imageUrl: "https://placehold.co/400x400/ADD8E6/000000?text=Oxford",
  },
  {
    name: "Wool Peacoat",
    category: "Jackets",
    color: "Charcoal",
    size: "M",
    price: 280.0,
    imageUrl: "https://placehold.co/400x400/36454F/ffffff?text=Peacoat",
  },
  {
    name: "Cardigan",
    category: "Sweaters",
    color: "Maroon",
    size: "L",
    price: 75.0,
    imageUrl: "https://placehold.co/400x400/800000/ffffff?text=Cardigan",
  },
  {
    name: "Dress Pants",
    category: "Pants",
    color: "Gray",
    size: "M",
    price: 85.0,
    imageUrl: "https://placehold.co/400x400/708090/ffffff?text=Dress+Pants",
  },
  {
    name: "Leather Belt",
    category: "Accessories",
    color: "Brown",
    size: "M",
    price: 40.0,
    imageUrl: "https://placehold.co/400x400/A52A2A/ffffff?text=Belt",
  },
  {
    name: "Beanie",
    category: "Accessories",
    color: "Orange",
    size: "One Size",
    price: 20.0,
    imageUrl: "https://placehold.co/400x400/FFA500/000000?text=Beanie",
  },
  {
    name: "Flannel Shirt",
    category: "Shirts",
    color: "Red Plaid",
    size: "XL",
    price: 58.0,
    imageUrl: "https://placehold.co/400x400/FF0000/ffffff?text=Flannel",
  },
  {
    name: "Jogger Pants",
    category: "Pants",
    color: "Black",
    size: "S",
    price: 50.0,
    imageUrl: "https://placehold.co/400x400/3b3b3b/ffffff?text=Joggers",
  },
  {
    name: "Canvas Slip-Ons",
    category: "Shoes",
    color: "Gray",
    size: "M",
    price: 60.0,
    imageUrl: "https://placehold.co/400x400/808080/ffffff?text=Slip-Ons",
  },
  {
    name: "Puffer Vest",
    category: "Vests",
    color: "Yellow",
    size: "L",
    price: 90.0,
    imageUrl: "https://placehold.co/400x400/FFFF00/000000?text=Vest",
  },
  {
    name: "Turtleneck Sweater",
    category: "Sweaters",
    color: "Black",
    size: "M",
    price: 85.0,
    imageUrl: "https://placehold.co/400x400/4d4d4d/ffffff?text=Turtleneck",
  },
  {
    name: "Denim Shorts",
    category: "Shorts",
    color: "Light Wash",
    size: "S",
    price: 48.0,
    imageUrl: "https://placehold.co/400x400/AEC6CF/000000?text=Denim+Shorts",
  },
  {
    name: "Sunglasses",
    category: "Accessories",
    color: "Black",
    size: "One Size",
    price: 110.0,
    imageUrl: "https://placehold.co/400x400/5d5d5d/ffffff?text=Sunglasses",
  },
  {
    name: "Wrist Watch",
    category: "Accessories",
    color: "Silver",
    size: "One Size",
    price: 350.0,
    imageUrl: "https://placehold.co/400x400/C0C0C0/000000?text=Watch",
  },
  {
    name: "Hawaiian Shirt",
    category: "Shirts",
    color: "Multi-color",
    size: "L",
    price: 42.0,
    imageUrl: "https://placehold.co/400x400/32CD32/000000?text=Hawaiian",
  },
  {
    name: "Straight-Fit Jeans",
    category: "Jeans",
    color: "Indigo",
    size: "XL",
    price: 88.0,
    imageUrl: "https://placehold.co/400x400/4B0082/ffffff?text=Jeans",
  },
  {
    name: "Leather Gloves",
    category: "Accessories",
    color: "Black",
    size: "L",
    price: 60.0,
    imageUrl: "https://placehold.co/400x400/6e6e6e/ffffff?text=Gloves",
  },
  {
    name: "Suede Jacket",
    category: "Jackets",
    color: "Tan",
    size: "M",
    price: 270.0,
    imageUrl: "https://placehold.co/400x400/D2B48C/000000?text=Suede+Jacket",
  },
  {
    name: "Cable-Knit Sweater",
    category: "Sweaters",
    color: "Ivory",
    size: "S",
    price: 95.0,
    imageUrl: "https://placehold.co/400x400/FFFFF0/000000?text=Sweater",
  },
  {
    name: "Pleated Shorts",
    category: "Shorts",
    color: "Navy",
    size: "L",
    price: 52.0,
    imageUrl: "https://placehold.co/400x400/191970/ffffff?text=Pleated",
  },
  {
    name: "Desert Boots",
    category: "Shoes",
    color: "Sand",
    size: "M",
    price: 140.0,
    imageUrl: "https://placehold.co/400x400/F4A460/000000?text=Desert+Boots",
  },
  {
    name: "Baseball Cap",
    category: "Accessories",
    color: "Royal Blue",
    size: "One Size",
    price: 25.0,
    imageUrl: "https://placehold.co/400x400/4169E1/ffffff?text=Cap",
  },
  {
    name: "Pocket Tee",
    category: "T-Shirts",
    color: "Olive",
    size: "XL",
    price: 26.0,
    imageUrl: "https://placehold.co/400x400/808000/ffffff?text=Pocket+Tee",
  },
  {
    name: "Corduroy Pants",
    category: "Pants",
    color: "Burgundy",
    size: "M",
    price: 78.0,
    imageUrl: "https://placehold.co/400x400/800020/ffffff?text=Cords",
  },
  {
    name: "Windbreaker Jacket",
    category: "Jackets",
    color: "Teal",
    size: "L",
    price: 85.0,
    imageUrl: "https://placehold.co/400x400/008080/ffffff?text=Windbreaker",
  },
  {
    name: "Quarter-Zip Sweatshirt",
    category: "Sweatshirts",
    color: "Heather Gray",
    size: "S",
    price: 60.0,
    imageUrl: "https://placehold.co/400x400/D3D3D3/000000?text=Quarter-Zip",
  },
  {
    name: "Tank Top",
    category: "T-Shirts",
    color: "White",
    size: "M",
    price: 18.0,
    imageUrl: "https://placehold.co/400x400/f2f2f2/000000?text=Tank+Top",
  },
  {
    name: "Work Boots",
    category: "Shoes",
    color: "Wheat",
    size: "XL",
    price: 190.0,
    imageUrl: "https://placehold.co/400x400/F5DEB3/000000?text=Work+Boots",
  },
  {
    name: "Scarf",
    category: "Accessories",
    color: "Plaid",
    size: "One Size",
    price: 35.0,
    imageUrl: "https://placehold.co/400x400/A0522D/ffffff?text=Scarf",
  },
  {
    name: "Blazer",
    category: "Jackets",
    color: "Navy",
    size: "L",
    price: 195.0,
    imageUrl: "https://placehold.co/400x400/000080/ffffff?text=Blazer",
  },
  {
    name: "Linen Shirt",
    category: "Shirts",
    color: "White",
    size: "M",
    price: 65.0,
    imageUrl: "https://placehold.co/400x400/f5f5f5/000000?text=Linen+Shirt",
  },
  {
    name: "Board Shorts",
    category: "Shorts",
    color: "Aqua",
    size: "M",
    price: 40.0,
    imageUrl: "https://placehold.co/400x400/00FFFF/000000?text=Board+Shorts",
  },
  {
    name: "V-Neck Sweater",
    category: "Sweaters",
    color: "Forest Green",
    size: "S",
    price: 80.0,
    imageUrl: "https://placehold.co/400x400/228B22/ffffff?text=V-Sweater",
  },
  {
    name: "Backpack",
    category: "Accessories",
    color: "Black",
    size: "One Size",
    price: 75.0,
    imageUrl: "https://placehold.co/400x400/7d7d7d/ffffff?text=Backpack",
  },
  {
    name: "Athletic Pants",
    category: "Pants",
    color: "Gray",
    size: "XL",
    price: 55.0,
    imageUrl: "https://placehold.co/400x400/909090/ffffff?text=Athletic+Pants",
  },
  {
    name: "Sandals",
    category: "Shoes",
    color: "Black",
    size: "L",
    price: 50.0,
    imageUrl: "https://placehold.co/400x400/8f8f8f/ffffff?text=Sandals",
  },
  {
    name: "Overcoat",
    category: "Jackets",
    color: "Camel",
    size: "M",
    price: 320.0,
    imageUrl: "https://placehold.co/400x400/C19A6B/000000?text=Overcoat",
  },
  {
    name: "Crew Socks",
    category: "Accessories",
    color: "White",
    size: "M",
    price: 12.0,
    imageUrl: "https://placehold.co/400x400/fafafa/000000?text=Socks",
  },
  {
    name: "Denim Shirt",
    category: "Shirts",
    color: "Chambray",
    size: "S",
    price: 62.0,
    imageUrl: "https://placehold.co/400x400/778899/ffffff?text=Denim+Shirt",
  },
  {
    name: "Relaxed Fit Jeans",
    category: "Jeans",
    color: "Stone Wash",
    size: "L",
    price: 90.0,
    imageUrl: "https://placehold.co/400x400/68838B/ffffff?text=Relaxed+Fit",
  },
  {
    name: "Fair Isle Sweater",
    category: "Sweaters",
    color: "Multi-color",
    size: "XL",
    price: 110.0,
    imageUrl: "https://placehold.co/400x400/4682B4/ffffff?text=Fair+Isle",
  },
  {
    name: "Gym Shorts",
    category: "Shorts",
    color: "Red",
    size: "M",
    price: 28.0,
    imageUrl: "https://placehold.co/400x400/B22222/ffffff?text=Gym+Shorts",
  },
  {
    name: "Driving Moccasins",
    category: "Shoes",
    color: "Navy",
    size: "M",
    price: 125.0,
    imageUrl: "https://placehold.co/400x400/2a2a8a/ffffff?text=Moccasins",
  },
  {
    name: "Fleece Jacket",
    category: "Jackets",
    color: "Blue",
    size: "S",
    price: 95.0,
    imageUrl: "https://placehold.co/400x400/6495ED/000000?text=Fleece+Jacket",
  },
  {
    name: "Thermal Shirt",
    category: "Shirts",
    color: "Cream",
    size: "L",
    price: 38.0,
    imageUrl: "https://placehold.co/400x400/FFFACD/000000?text=Thermal",
  },
  {
    name: "Knit Beanie",
    category: "Accessories",
    color: "Charcoal",
    size: "One Size",
    price: 22.0,
    imageUrl: "https://placehold.co/400x400/464646/ffffff?text=Knit+Beanie",
  },
  {
    name: "Shawl Cardigan",
    category: "Sweaters",
    color: "Oatmeal",
    size: "M",
    price: 90.0,
    imageUrl: "https://placehold.co/400x400/D4C4A8/000000?text=Shawl",
  },
  {
    name: "Cargo Pants",
    category: "Pants",
    color: "Olive Drab",
    size: "XL",
    price: 68.0,
    imageUrl: "https://placehold.co/400x400/6B8E23/ffffff?text=Cargo+Pants",
  },
  {
    name: "Espadrilles",
    category: "Shoes",
    color: "Natural",
    size: "S",
    price: 70.0,
    imageUrl: "https://placehold.co/400x400/F0E68C/000000?text=Espadrilles",
  },
  {
    name: "Anorak Jacket",
    category: "Jackets",
    color: "Orange",
    size: "L",
    price: 115.0,
    imageUrl: "https://placehold.co/400x400/FF4500/ffffff?text=Anorak",
  },
  {
    name: "Rugby Shirt",
    category: "Shirts",
    color: "Striped",
    size: "M",
    price: 55.0,
    imageUrl: "https://placehold.co/400x400/0000CD/ffffff?text=Rugby",
  },
  {
    name: "Leather Wallet",
    category: "Accessories",
    color: "Dark Brown",
    size: "One Size",
    price: 50.0,
    imageUrl: "https://placehold.co/400x400/5C4033/ffffff?text=Wallet",
  },
  {
    name: "Hooded Sweatshirt",
    category: "Sweatshirts",
    color: "Burgundy",
    size: "XL",
    price: 68.0,
    imageUrl: "https://placehold.co/400x400/900020/ffffff?text=Hooded",
  },
  {
    name: "Twill Shorts",
    category: "Shorts",
    color: "Stone",
    size: "L",
    price: 42.0,
    imageUrl: "https://placehold.co/400x400/B9B5A3/000000?text=Twill+Shorts",
  },
  {
    name: "Boat Shoes",
    category: "Shoes",
    color: "Tan",
    size: "M",
    price: 110.0,
    imageUrl: "https://placehold.co/400x400/D2B48C/000000?text=Boat+Shoes",
  },
  {
    name: "Waxed Canvas Jacket",
    category: "Jackets",
    color: "Brown",
    size: "L",
    price: 260.0,
    imageUrl: "https://placehold.co/400x400/8B4513/ffffff?text=Waxed+Jacket",
  },
];
